format = """
$username@$hostname \
$directory\
$git_branch\
$status\
$character
"""

right_format = "$cmd_duration$time"

[time]
disabled = false
format = "[$time]($style)"
style = "bright-black"

[line_break]
disabled = true

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "#bd93f9"

[username]
show_always = true
format = "[$user]($style)"
style_user = "#8be9fd"

[status]
disabled = false
format = '[\[$status\]]($style)'

[directory]
truncate_to_repo = false
truncation_length = 80
style = "#50fa7b"

[git_branch]
format = '[\($branch(:$remote_branch)\)]($style) '
style = "#ffffff"

[cmd_duration]
style = "#f1fa8c"

[character]
error_symbol = "[❯](#ff5555)"
success_symbol = "[❯](#50fa7b)"
